### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by rookiexiao123** [Justin-Tan/high-fidelity-generative-compression#19]
python compress.py -i data/originals/ -ckpt model/hific_med.pt --reconstruct
later

“
12:58:16 INFO - compress_and_decompress: Starting compression...
  0%|                                                                                                       | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "compress.py", line 240, in <module>
    main()
  File "compress.py", line 237, in main
    compress_and_decompress(args)
  File "compress.py", line 143, in compress_and_decompress
    for idx, (data, bpp, filenames) in enumerate(tqdm(eval_loader), 0):
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\site-packages\tqdm\std.py", line 1171, in __iter__
    for obj in iterable:
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\DELL\Anaconda3\envs\torch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
”
please help me.What's wrong with me?

**Comment by JXH-SHU** [comment]
HI！Have you solved this problem？ I also encountered this problem, don’t know how to solve it

**Comment by kuro-z** [comment]
me too.please help us.
